[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve = "Da4dAJgYgs6Z4pcWWZzzvpdprtUB9hUDvoHkyJpQNYBz"

[programs.localnet]
bonding_curve = "Da4dAJgYgs6Z4pcWWZzzvpdprtUB9hUDvoHkyJpQNYBz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/wotori/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
