[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve = "GMjvbDmasN1FyYD6iGfj5u8EETdk9gTQnyoZUQA4PVGT"

[programs.localnet]
bonding_curve = "GMjvbDmasN1FyYD6iGfj5u8EETdk9gTQnyoZUQA4PVGT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/wotori/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
