[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve = "Ht1kvf1fWgLgoEs8f5npkqpDFn7Hq5EKFNpVqUwWK6mX"

[programs.localnet]
bonding_curve = "Ht1kvf1fWgLgoEs8f5npkqpDFn7Hq5EKFNpVqUwWK6mX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/wotori/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build && cp target/idl/*.json ./idl/ && cp target/types/*.ts ./idl/"