[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve = "BqrcBeCGtK1qasqykoFydSEV31iEYTuPnUW1mpsptv5W"

[programs.localnet]
bonding_curve = "BqrcBeCGtK1qasqykoFydSEV31iEYTuPnUW1mpsptv5W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/wotori/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
