[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_bonding_curve = "E48ijHDaZqdVBiGgCGGJRQTM373TsjYPGv8rpVzu4P9R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/wotori/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
